version: '3.8'

services:

  backend:
    container_name: smoothsick-api
    image: devstoni/smoothsick-api:0.0.3
    ports:
      - $HOST_SERVER_PORT:$SERVER_PORT
    environment:
      - NODE_ENV=production
      - PORT=$SERVER_PORT
      - DB_URI=$DB_URL
      - CLOUDINARY_NAME=$CLOUDINARY_NAME
      - CLOUDINARY_KEY=$CLOUDINARY_KEY
      - CLOUDINARY_SECRET=$CLOUDINARY_SECRET
      - FRONT_URI=$CLIENT_URL
    networks:
      - net

  frontend:
    container_name: smoothsick-client
    image: devstoni/smoothsick-front:0.0.3
    ports:
      - $HOST_CLIENT_PORT:3002
    stdin_open: true
    environment:
      - VITE_BACKEND=$SERVER_URL
      - VITE_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
    networks:
      - net

networks:
  net:
    external: false

  
