version: '3.8'

services:

  backend:
    container_name: servsmoothapi
    image: devstoni/smoothsick-api:0.0.2
    ports:
      - '8082:8082'
    environment:
      - NODE_ENV=production
      - PORT=8082
      - DB_URI_PROD=mongodb+srv://devs-toni:aSJazxDPdxwBiLZg@cluster0.hwmnwed.mongodb.net/smoothsick

  frontend:
    container_name: servsmoothfrnt
    image: devstoni/smoothsick-front:0.0.3
    ports:
      - '3002:3002'
    stdin_open: true
    environment:
      - VITE_BACKEND=https://smoothsick-api.arcprojects.es/

networks:
  default:
    name: servsmoothops_net
  
