version: '3.8'

services:

  database:
    container_name: smoothsick-database
    image: mongo:6-jammy
    environment:
      MONGO_INITDB_DATABASE: $DB_NAME
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_PORT:27017
    volumes:
      - data:/smoothsick-data
    command: mongod --auth --port 27017
    networks:
      - net

  backend:
    container_name: smoothsick-api
    image: devstoni/smoothsick-api:0.0.8
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - $SERVER_HOST_PORT:$SERVER_PORT
    environment:
      - NODE_ENV=production
      - PORT=$SERVER_PORT
      - DB_URI=$DB_URL
      - CLOUDINARY_NAME=$CLOUDINARY_NAME
      - CLOUDINARY_KEY=$CLOUDINARY_KEY
      - CLOUDINARY_SECRET=$CLOUDINARY_SECRET
      - FRONT_URI=$CLIENT_URL
    networks:
      - net

  frontend:
    container_name: smoothsick-client
    image: devstoni/smoothsick-front:0.0.4
    ports:
      - $CLIENT_HOST_PORT:3002
    stdin_open: true
    environment:
      - VITE_BACKEND=$SERVER_URL
      - VITE_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
    networks:
      - net

networks:
  net:
    external: false

volumes:
  data:

    


